-- IoT Device Management Database
-- Description: Schema for managing IoT devices.
-- Tables included:
--   - Devices: Information about the IoT devices.
--   - Sensors: Each device can have multiple sensors.
--   - Sensor_Readings: Recorded readings from sensors.
--   - Alerts: Alerts generated by abnormal sensor data.
--   - Device_Groups: Groups for organizing devices.
--   - Group_Memberships: Many-to-many relationship between devices and groups.

CREATE TABLE Devices (
    device_id INT AUTO_INCREMENT PRIMARY KEY,
    device_name VARCHAR(100) NOT NULL,
    description TEXT,
    location VARCHAR(255),
    status ENUM('active', 'inactive', 'maintenance') DEFAULT 'active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Sensors (
    sensor_id INT AUTO_INCREMENT PRIMARY KEY,
    device_id INT,
    sensor_type VARCHAR(50) NOT NULL,  -- e.g., temperature, humidity
    unit VARCHAR(20),
    installation_date DATE,
    FOREIGN KEY (device_id) REFERENCES Devices(device_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Sensor_Readings (
    reading_id INT AUTO_INCREMENT PRIMARY KEY,
    sensor_id INT,
    reading_value DECIMAL(10,4),
    reading_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sensor_id) REFERENCES Sensors(sensor_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Alerts (
    alert_id INT AUTO_INCREMENT PRIMARY KEY,
    device_id INT,
    sensor_id INT,
    message TEXT,
    alert_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    severity ENUM('low', 'medium', 'high'),
    FOREIGN KEY (device_id) REFERENCES Devices(device_id) ON DELETE CASCADE,
    FOREIGN KEY (sensor_id) REFERENCES Sensors(sensor_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Device_Groups (
    group_id INT AUTO_INCREMENT PRIMARY KEY,
    group_name VARCHAR(100) NOT NULL,
    description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Group_Memberships (
    group_id INT,
    device_id INT,
    PRIMARY KEY (group_id, device_id),
    FOREIGN KEY (group_id) REFERENCES Device_Groups(group_id) ON DELETE CASCADE,
    FOREIGN KEY (device_id) REFERENCES Devices(device_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
